[package]
name = "redscript-parser"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
chumsky.workspace = true
redscript-ast = { path = "../ast" }

[dev-dependencies]
pretty_assertions.workspace = true

[lints]
workspace = true
